### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by kzzanuda** [gbukin/psuti-ctf-template-project#1]
Hi!
I place my secret token in config file and push this in my repo.
Can u help me? I want to delete this commit, but it was in history.

**Comment by gbukin** [comment]
Hi!
You can't delete or change pushed public commit. You can do new commit without secret token, but as you say: it stay in history.

The only option is to remove the fork and create new one, without commits with secret token.

Hope i help you with this trouble :)
